### ISSUE TITLE
I'm not able to install pyvsc package, it fails when handling the pyboolector module

### ISSUE THREAD

**Issue by mahawana** [fvutils/pyvsc#171]
**Hello, 
I'm trying to install this new package "pyvsc", but it generates an error that I can't seem to shake. **   

c:\Users\hawan\Downloads\emacs_dir\emacs\bin>  pip install pyvsc
pip install pyvsc
Collecting pyvsc
  Using cached pyvsc-0.8.1.3466255343-py2.py3-none-any.whl (160 kB)
Collecting pyboolector>=3.2.2
  Downloading PyBoolector-3.2.2.20230105.5.tar.gz (21 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  error: subprocess-exited-with-error
  
  python setup.py egg_info did not run successfully.
  exit code: 1
  
  [7 lines of output]
  Traceback (most recent call last):
    File "<string>", line 2, in <module>
    File "<pip-setuptools-caller>", line 34, in <module>
    File "C:\Users\hawan\AppData\Local\Temp\pip-install-6efnoabb\pyboolector_302b91c0cf0c4a7eb673d33dc9dba1bf\setup.py", line 14, in <module>
      with open(cmakelists_txt, "r") as f:
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\hawan\\AppData\\Local\\Temp\\pip-install-6efnoabb\\CMakeLists.txt'
  [end of output]

**In reading posts associated with pyboolector,  I also tried installing pyboolector seperately, but I get the same error:** 
         c:\Users\hawan\Downloads\emacs_dir\emacs\bin>   -m pip install pyboolector

**I'm not versed in the installation flow...any help is much appreciated. 
my environment info: 
  * Windows 11
  * python  3.11.1
  **

**Comment by alwilson** [comment]
I think PyBoolector might only have binaries built for Linux and Mac, while Windows will have to build from source. Hence why it's grabbing a tar.gz rather than the whl file. I'm guessing something with cmake is wrong or not installed, or perhaps something with the windows build process is broken?

Source and pre-built wheel/binaries for Linux/Mac:
https://pypi.org/project/PyBoolector/3.2.2.20230105.5/#files

**Comment by mballance** [comment]
@alwilson, @mahawana, Yes, pre-built binaries are currently only available for Linux and Mac. Unfortunately, Boolector currently depends on using mingw/msys compilers on Windows, and pre-built binary packages for Python require that the Visual Studio compiler be used.

@mahawana, you could try compiling Boolector and its Python extension on Windows using the instructions provided by the Boolector project. This should allow you to use PyVSC.

**Comment by 167rgc911** [comment]
@mahawana upgrade your pip

`pip install --upgrade pip`

https://github.com/Boolector/boolector/issues/175
