### ISSUE TITLE
install error for latest version macos

### ISSUE THREAD

**Issue by hanfeng0114** [fvutils/pyvsc#187]
command: pip3 install pyvsc

os info:
3.4.1 (c) 
python 3.10.8

Error message:

Collecting pyvsc
  Using cached pyvsc-0.8.3.4340109521-py2.py3-none-any.whl (160 kB)
Collecting pyboolector>=3.2.2 (from pyvsc)
  Using cached PyBoolector-3.2.2.20230110.4.tar.gz (21 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/lw/206p84bs4qvfh3s2_k0212fr0000gp/T/pip-install-53_wlhj9/pyboolector_89853a0578fd4cdb9e64a3223dd34d72/setup.py", line 14, in <module>
          with open(cmakelists_txt, "r") as f:
      FileNotFoundError: [Errno 2] No such file or directory: '/private/var/folders/lw/206p84bs4qvfh3s2_k0212fr0000gp/T/pip-install-53_wlhj9/CMakeLists.txt'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by mballance** [comment]
Just to confirm, are you using macos on Apple silicon (Arm architecture) or Intel (x86 architecture)? I suspect the issue is that the PyPi release of Boolector uses Python 3.9, while you're using Python 3.10. I'll investigate

**Comment by hanfeng0114** [comment]
It is Intel(x86 architecutre).
Thanks for the response.

**Comment by hanfeng0114** [comment]
What's more, is there any plan to update PyPi to support latest Python3.10?
