### ISSUE TITLE
Cannot constrain attribute inside a rand_attr inside a rand_list

### ISSUE THREAD

**Issue by felixdube** [fvutils/pyvsc#224]
Hi,
I have a list of random objects which contains other random objects. I am trying to constraint the values inside the embedded random objects, but it fails. Is this a bug or am I doing something illegal?

Here's a simplified example:
```
@vsc.randobj
class Field(object):

    def __init__(self):
        self.c = vsc.rand_uint8_t()


@vsc.randobj
class Child(object):

    def __init__(self):
        self.b = vsc.rand_attr(Field())


@vsc.randobj
class Parent(object):

    def __init__(self):
        self.a = vsc.rand_list_t(Child(), 2)

    @vsc.constraint
    def eq_c(self):
        self.a[0].b.c == self.a[1].b.c


item = Parent()
```

It fails during instantiation with the error `AttributeError: 'expr' object has no attribute 'c'`

Thanks,
Felix

**Comment by alwilson** [comment]
There's a unit test and example for a single layer of nesting, but the two layer unit tests uses `rand_list_t` for each layer. I wonder if `rand_list_t` is doing something extra to support nesting that's missing from `rand_attr_t`.

https://github.com/fvutils/pyvsc/blob/0a9a1d62f10db820eec82525893a61f427c386d5/ve/unit/test_compound_obj.py#L162-L190

Your example using `rand_list_t` for each layer of nesting:
```python3
@vsc.randobj
class Field(object):
    def __init__(self):
        self.c = vsc.rand_uint8_t()

@vsc.randobj
class Child(object):
    def __init__(self):
        self.b = vsc.rand_list_t(vsc.rand_attr(Field()), 1)

@vsc.randobj
class Parent(object):
    def __init__(self):
        self.a = vsc.rand_list_t(vsc.rand_attr(Child()), 2)

    @vsc.constraint
    def eq_c(self):
        self.a[0].b[0].c == self.a[1].b[0].c

item = Parent()
item.randomize()
print(item.a[0].b[0].c, item.a[1].b[0].c)
```

**Comment by alwilson** [comment]
Well I looked again, and `vsc.rand_attr` can be nested without issue. I don't think the expression parsing supports more than simple scalar types nested under `rand_list_t`. The randomize(debug=1) output doesn't seem to do the right thing either and treats sub-fields as array indices rather than the rand_attr/object they are.

```python3
@vsc.randobj
class Child(object):
    def __init__(self):
        self.b = vsc.rand_uint8_t()

@vsc.randobj
class Parent(object):
    def __init__(self):
        self.a = vsc.rand_list_t(vsc.rand_attr(Child()), 2)

    @vsc.constraint
    def eq_c(self):
        self.a[0].b == self.a[1].b
```
Debug output for constraint:
```python3
    constraint eq_c {
        (a[0].[0] == a[1].[0]);
    }
```

I played around in the debugger and came up with something very hacky that works. I think the TODO in here has something to do with the limitation/bug you're seeing. My hack passes all the unit tests, so maybe I'm close?

https://github.com/fvutils/pyvsc/blob/0a9a1d62f10db820eec82525893a61f427c386d5/src/vsc/types.py#L1023-L1032

My hack:
```diff
diff --git a/src/vsc/types.py b/src/vsc/types.py
index 80ad028..11a3b43 100644
--- a/src/vsc/types.py
+++ b/src/vsc/types.py
@@ -1025,12 +1025,17 @@ class list_t(object):
         if get_expr_mode():
             # TODO: must determine whether we're within a foreach or just on our own
             to_expr(k)
-            idx_e = pop_expr()
-                 
-            return expr_subscript(ExprArraySubscriptModel(
-                ExprFieldRefModel(self.get_model()),
-                idx_e))
-            
+
+            # Attempt to stop treating everything as an array if it has a backing array
+            # dynamic constraint unit test uses attr instead of rand_attr?
+            if isinstance(k, int) and len(self.backing_arr) > 0 and self.t._int_field_info.is_rand:
+                return self.backing_arr[k]
+            else:
+                idx_e = pop_expr()
+                return expr_subscript(ExprArraySubscriptModel(
+                    ExprFieldRefModel(self.get_model()),
+                    idx_e))
+
 #             if is_foreach_arr(self):
 #                 to_expr(k)
 #                 idx_e = pop_expr()
```

**Comment by mballance** [comment]
Hey @alwilson, looks like we both ended up investigating at the same time. You're definitely on the right path to override __getattr__ as a way to access fields within an expression. My fix is very similar, but just moved up a level -- to the core 'expr' class that represents expressions within user Python code.

https://github.com/fvutils/pyvsc/blob/1061db10dc28bf61ebfbe4dab5d10c6f6a1e4b29/src/vsc/types.py#L178-L199

So, why is this necessary?
- As long as we're unconditionally referencing fields (eg a.b.c), PyVSC represents references as a direct reference to the Python field (eg FieldRef(<a.b.c>)). The convenient thing about these refs is that they're really simple.
- An array index reference introduces the possibility that the element we access will depend on a constraint expression (eg an index within a foreach). Consequently, these references are represented as indirect references that are resolved during the solve process. These references are very flexible, but they require much more in terms of operator overloading.

The code I committed a minute ago resolves the issues with the testcase. @felixdube, please try it out and let us know if you face further issues.

**Comment by alwilson** [comment]
@mballance Haha, yup! I've been curious to learn more how pyvsc parses constraints so it's good exploration either way. Unfortunately the vscode python debugger will fail sometimes when stepping through pyvsc whereas it doesn't otherwise.

I tried out your most recent change, and constructing the object no longer fails, but randomization does fail. If you add `item.randomize()` to that unit test it fails with:
```python3
AttributeError: 'ExprIndexedFieldRefModel' object has no attribute 'fm'
```

Also, it looks like DEBUG_EN was left on and prints independent of debug=1.

**Comment by mballance** [comment]
Good catch, @alwilson. Debug prints are now disabled, and randomization works.

**Comment by felixdube** [comment]
Thanks @alwilson @mballance !!
I just tested your latest changes, but I am now getting a different error.

(Part of the output has been replaced with asterisks for privacy)
```
Traceback (most recent call last):
  File "/opt/python/lib/python3.10/site-packages/pyuvm/extension_classes.py", line 41, in test
    await uvm_root().run_test(cls)
  File "/opt/python/lib/python3.10/site-packages/pyuvm/s13_uvm_component.py", line 412, in run_test
    self.uvm_test_top = factory.create_component_by_name(
  File "/opt/python/lib/python3.10/site-packages/pyuvm/s08_factory_classes.py", line 302, in create_component_by_name
    new_obj = self.create_component_by_type(requested_type,
  File "/opt/python/lib/python3.10/site-packages/pyuvm/s08_factory_classes.py", line 278, in create_component_by_type
    new_comp = new_type(name, parent)
  File "/home/fdube/.local/lib/python3.10/site-packages/vsc/rand_obj.py", line 78, in __init__
    super().__init__(*args, **kwargs)
  File "/site/home/fdube/****.py", line 17, in __init__
    self.cfg = vsc.rand_attr(**.create("cfg"))
  File "/opt/python/lib/python3.10/site-packages/pyuvm/s05_base_classes.py", line 107, in create
    new_obj = uvm_factory().create_object_by_type(cls, name=name)
  File "/opt/python/lib/python3.10/site-packages/pyuvm/s08_factory_classes.py", line 229, in create_object_by_type
    return new_type(name)
  File "/home/fdube/.local/lib/python3.10/site-packages/vsc/rand_obj.py", line 82, in __init__
    self.build_field_model(None)
  File "/home/fdube/.local/lib/python3.10/site-packages/vsc/rand_obj.py", line 211, in build_field_model
    raise e
  File "/home/fdube/.local/lib/python3.10/site-packages/vsc/rand_obj.py", line 208, in build_field_model
    fo.c(self)
  File "/site/home/fdube/****.py", line 28, in **
    self.**[i].**[j].**.** == self.**[i - 1].**[
  File "/home/fdube/.local/lib/python3.10/site-packages/vsc/types.py", line 181, in __getattr__
    fm_t = Expr2FieldTypeVisitor().fieldtype(em)
  File "/home/fdube/.local/lib/python3.10/site-packages/vsc/visitors/expr2fieldtype_visitor.py", line 25, in fieldtype
    e.accept(self)
  File "/home/fdube/.local/lib/python3.10/site-packages/vsc/model/expr_indexed_field_ref_model.py", line 57, in accept
    v.visit_expr_indexed_fieldref(self)
  File "/home/fdube/.local/lib/python3.10/site-packages/vsc/visitors/expr2fieldtype_visitor.py", line 49, in visit_expr_indexed_fieldref
    e.root.accept(self)
  File "/home/fdube/.local/lib/python3.10/site-packages/vsc/model/expr_array_subscript_model.py", line 58, in accept
    v.visit_expr_array_subscript(self)
  File "/home/fdube/.local/lib/python3.10/site-packages/vsc/visitors/expr2fieldtype_visitor.py", line 62, in visit_expr_array_subscript
    t.accept(self)
AttributeError: 'NoneType' object has no attribute 'accept'

```

**Comment by mballance** [comment]
Hi @felixdube, that's unfortunate... If you can extract a standalone testcase that would be ideal. If not, please try changing the code near line 64 in expr2fieldtype_visitor.py as follows:
Original:
```python
        t = self.type
        self.type = None
        t.accept(self)
```

Change:
```python
        if self.type is not None:
            t = self.type
            self.type = None
            t.accept(self)
```

**Comment by felixdube** [comment]
Yes, it works with that change. Just for completeness, here is the updated testcase that hit the error. Thank you @mballance !!
```Python
import vsc


@vsc.randobj
class Field(object):

    def __init__(self):
        print("Field")
        self.d = vsc.rand_uint8_t()


@vsc.randobj
class Child1(object):

    def __init__(self):
        print("Child")
        self.b = vsc.rand_list_t(Child2(), 2)


@vsc.randobj
class Child2(object):

    def __init__(self):
        print("Child")
        self.c = vsc.rand_attr(Field())


@vsc.randobj
class Parent(object):

    def __init__(self):
        print("Parent")
        self.a = vsc.rand_list_t(Child1(), 2)

    @vsc.constraint
    def eq_c(self):
        self.a[0].b[0].c.d == self.a[1].b[0].c.d


item = Parent()
item.randomize()
print(f"{item.a[0].b[0].c.d} {item.a[1].b[0].c.d}")
```

**Comment by felixdube** [comment]
However, with those new changes, there are some class that used to work, but does not anymore. Here is an example:
```Python
import vsc


@vsc.randobj
class Item(object):

    def __init__(self):
        self.a = vsc.list_t(vsc.rand_list_t(vsc.rand_bit_t(2), 2))


item = Item()
```

It fails with `Exception: Failed to obtain field from expression ((1 * <unknown-array>.<unknown-array>[0]) * <unknown-array>.<unknown-array>[1])`

**Comment by felixdube** [comment]
The previous construct might seem weird, but I have some more code in pre_randomize that appends more rand_list to the list.
```Python
def pre_randomize(self):
        for _ in range(2):
            self.vlan_monitor.append(vsc.rand_list_t(vsc.rand_bit_t(2), 2))
```

**Comment by mballance** [comment]
Many thanks for the testcases, @felixdube. I believe I've addressed both in the latest build (https://pypi.org/project/pyvsc/0.9.1.10086043874). Please give it a try!
