### ISSUE TITLE
Issue with Part-select in coverpoints

### ISSUE THREAD

**Issue by ishita-71** [fvutils/pyvsc#93]
Hi,
I am trying to select a part of the coverpoint but it is giving the below error even my  `self.a` is of  `vsc.bit_t()` type
TestCase:
```python3
import vsc
from vsc import *
 
@vsc.randobj
class my_item_c(object):
    def __init__(self):
        self.a = vsc.bit_t(8)
    
@vsc.covergroup
class my_cg(object):
    def __init__(self):
         self.with_sample(dict(
        it=my_item_c()))

         self.cp_my = vsc.coverpoint(lambda:self.it.a[7:2],
                                            bins={
                                                "a": vsc.bin_array([], [0, 3])
                                            }
                                            )
# Create an instance of the covergroup
my_cg_i = my_cg()
# Create an instance of the item class
my_item_i = my_item_c()
my_cg_i.sample(my_item_i)


```

Output:
`Traceback (most recent call last):
  File "example.py", line 25, in <module>
    my_cg_i.sample(my_item_i)
  File "/home/ishita/.local/lib/python3.6/site-packages/vsc/coverage.py", line 132, in sample
    model.sample()
  File "/home/ishita/.local/lib/python3.6/site-packages/vsc/model/covergroup_model.py", line 63, in sample
    cp.sample()
  File "/home/ishita/.local/lib/python3.6/site-packages/vsc/model/coverpoint_model.py", line 112, in sample
    b.sample()
  File "/home/ishita/.local/lib/python3.6/site-packages/vsc/model/coverpoint_bin_array_model.py", line 58, in sample
    val = int(self.cp.get_val())
  File "/home/ishita/.local/lib/python3.6/site-packages/vsc/model/coverpoint_model.py", line 132, in get_val
    self.target_val_cache = self.target.val()
  File "/home/ishita/.local/lib/python3.6/site-packages/vsc/model/expr_ref_model.py", line 34, in val
    return self.ref()
  File "example.py", line 15, in <lambda>
    self.cp_my = vsc.coverpoint(lambda:self.it.a[7:2],
TypeError: 'int' object is not subscriptable`

**Comment by mballance** [comment]
Hi @ishita-71,
    I've investigated a bit, and can see what is happening. Some of the Python operator overloading that is used to make it easy to get values out of random-class fields is getting in the way of performing operations on the field value. I've recently learned some new ways of treating primitive Python values (eg int) as class objects, and will work to enhance the library to support this directly. Until then, you can use shift and mask to implement the same functionality:

```
                self.cp_my = vsc.coverpoint(lambda: ((self.it.a >> 2) & 0x3F),
                                            bins={
                                                "a": vsc.bin_array([], [0, 3])
                                            }
                                            )
```

Best Regards,
Matthew

**Comment by mballance** [comment]
Hi @ishita-71,
    I've added this enhancement in the 0.4.5 release, and can confirm that your testcase runs properly. 

Best Regards,
Matthew

**Comment by ishita-71** [comment]
Hi mballance,
I tried with the fix you provided. for earlier test it passed but for the below case it is still giving same error
```python3
import vsc
from vsc import *
     
@vsc.covergroup
class my_cg(object):
    def __init__(self):
         self.with_sample(a = vsc.bit_t(32))

         self.cp_my = vsc.coverpoint(lambda:self.a[7:2],
                                            bins={
                                                "a": vsc.bin_array([], [0, 3])
                                            }
                                            )
# Create an instance of the covergroup
my_cg_i = my_cg()
my_cg_i.sample(1)
```
output
`Traceback (most recent call last):
  File "example.py", line 24, in <module>
    my_cg_i.sample(1)
  File "/home/ishita/.local/lib/python3.6/site-packages/vsc/coverage.py", line 149, in sample
    model.sample()
  File "/home/ishita/.local/lib/python3.6/site-packages/vsc/model/covergroup_model.py", line 67, in sample
    cp.sample()
  File "/home/ishita/.local/lib/python3.6/site-packages/vsc/model/coverpoint_model.py", line 127, in sample
    b.sample()
  File "/home/ishita/.local/lib/python3.6/site-packages/vsc/model/coverpoint_bin_array_model.py", line 58, in sample
    val = int(self.cp.get_val())
  File "/home/ishita/.local/lib/python3.6/site-packages/vsc/model/coverpoint_model.py", line 153, in get_val
    self.target_val_cache = self.target.val()
  File "/home/ishita/.local/lib/python3.6/site-packages/vsc/model/expr_ref_model.py", line 34, in val
    return self.ref()
  File "example.py", line 15, in <lambda>
    self.cp_my = vsc.coverpoint(lambda:self.a[7:2],
TypeError: 'int' object is not subscriptable`
Can you help me with this?

**Comment by ishita-71** [comment]
I am not open this issue again so creating new one
